name: CI/CD to GitOps with pre-check.

on:
  push:
    branch:
      - main 

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_KEY }}

  update_the_image_test:
    name: Update image in GitOps repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: MichaelFarook/gitops-env
          token: ${{ secrets.GITOPS_KEY }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV
        
      - name: Update Image Version in the related GitOps repo values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'environments/production/values.yaml'
          propertyPath: 'applications.frontend_version'
          value: prod-${{ github.sha }}
          repository: MichaelFarook/gitops-env
          branch: main
          targetBranch: main
          message: 'Update workers Image Version to ${{ github.sha }} frontend'
          token: ${{ secrets.GITOPS_KEY }}
