name: CI/CD for web application

on:
  push:
    branch:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV
        
      - name: Build and Push Docker Image
        id: build-and-push-docker-image
        run: |
          docker build \
            --tag ${{ secrets.DOCKER_ACCOUNT }}/web-app:${TAG} \
            .

          docker push ${{ secrets.DOCKER_ACCOUNT }}/web-app:${TAG}

  update_the_image:
    name: Update the Image version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV
    
    - name: Update Image Version
      id: update-image
      uses: mikefarah/yq@master
      with:
        cmd: |
          yq eval '.image.tag = strenv(TAG)' -i helm/values.yaml
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes
