## In step of developing
#
#name: CI/CD to GitOps
#
#on:
#  workflow_dispatch:
#
#jobs:
#  push_to_registry:
#    name: Push Docker image to Docker Hub
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v3
#
#      - name: Log in to the Docker Hub
#        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      
#      - name: Add SHORT_SHA env property with commit short sha
#        run: echo "TAG=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV
#        
#      - name: Build and Push Docker Image
#        id: build-and-push-docker-image
#        run: |
#          docker build \
#            --tag ${{ secrets.DOCKER_ACCOUNT }}/web-app:${TAG} \
#            .
#
#          docker push ${{ secrets.DOCKER_ACCOUNT }}/web-app:${TAG}
#
#  update_the_image:
#    name: Update image in GitOps repo
#    runs-on: ubuntu-latest
#    steps:
#      - name: Update image in related HelmChart values.yaml
#          uses: fjogeleit/yaml-update-action@master
#          with:
#            valueFile: 'charts/benga-worker/values.yaml'
#            targetBranch: master
#            propertyPath: 'image.tag'
#            token: ${{ secrets.CD_TOKEN }}
#            value: ${{ github.sha }}
#            message: 'Update workers Image Version to ${{ github.sha }}
